name: Get code and install depedencies
description: Get a python code and install all required librariess
inputs:
  package_name: 
    description: Ptyhons package name
    required: true
  app_name:
    description: The app name
    required: true
    default: $GITHUB_REPOSITORY
outputs:
  test_value1: ${{ steps.install.outputs.test1 }}
  test_value2: ${{ steps.install.outputs.test2 }}
    
runs:
  using: 'composite'
  steps:
    - name: install depedencies
      id: install
      run: |
        pip install ${{ inputs.package_name }}
        echo "${{ inputs.app_name }}"
        echo "test1=123" >> $GITHUB_OUTPUT
        echo "test2=123" >> $GITHUB_OUTPUT
      shell: bash
