name: Output information
on: workflow_dispatch

jobs:
  info:
    env:
      name: 'Bartek'
      age: 25
    runs-on: ubuntu-latest
    name: Info job
    outputs:
      var1: ${{ steps.info.outputs.var1 }}
      var2: ${{ steps.info.outputs.var2 }}
    steps:
      - name: Output GitHub context
        id: info
        run: |
          echo "var1=111111" >> GITHUB_OUTPUT
          echo "var2=222222" >> GITHUB_OUTPUT
          echo "$Branch: {{ github.ref }}"
          echo "Rep: ${{ github.repository }}"
          echo "User: ${{ github.actor }}"
          echo "Event name: ${{ github.event_name }}"
          echo "Commit: ${{ github.sha }}"
          echo "OS ${{ github.os }}"
          echo "${{ secrets.USER }}"
          echo "${{ secrets.PASSWORD }}"
          echo "${{ job.status }}"
          echo "${{ job.services }}"
          echo "${{ steps.status }}"
          echo "${{ steps.info.conclusion }}"
          echo "${{ steps.info.outputs.var1 }}"
          echo "${{ steps.info.outputs.var2 }}"
