name: Output information
on: workflow_dispatch

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Output GitHub context
        run: |
          echo "${{ github.ref }}"
          echo "${{ github.repository }}"
          echo "${{ github.actor }}"
          echo "${{ github.event_name }}"
          echo "${{ github.sha }}"
          echo "${{ github.os }}"
