name: Output information
on: workflow_dispatch

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Output GitHub context
        run: |
          echo "$Branch: {{ github.ref }}"
          echo "Rep: ${{ github.repository }}"
          echo "User: ${{ github.actor }}"
          echo "Event name: ${{ github.event_name }}"
          echo "Commit: ${{ github.sha }}"
          echo "OS${{ github.os }}"
